# Generated by Django 5.0.6 on 2024-08-12 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users'),
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.JSONField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='DocOsge.doctorinformation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users')),
            ],
        ),
    ]
