# Generated by Django 5.0.6 on 2024-08-12 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0002_alter_doctorinformation_user_doctoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='DocOsge.doctorinformation'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users'),
        ),
    ]
