# Generated by Django 5.0.6 on 2024-08-11 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0005_rename_availibility_doctoravailability_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='DocOsge.doctorinformation'),
        ),
    ]
