# Generated by Django 5.0.6 on 2024-08-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0006_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='doctor',
            new_name='doctorInformation',
        ),
    ]
