# Generated by Django 5.0.6 on 2024-08-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0006_doctoravailability_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='user',
        ),
    ]
