# Generated by Django 5.0.6 on 2024-08-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0007_remove_doctoravailability_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users'),
            preserve_default=False,
        ),
    ]
