# Generated by Django 5.0.6 on 2024-07-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttypes',
            name='account_type',
            field=models.CharField(max_length=50),
        ),
    ]
