# Generated by Django 5.0.6 on 2024-08-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
