# Generated by Django 5.0.6 on 2024-07-03 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0002_alter_accounttypes_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccounttypes',
            old_name='account_type_id',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='useraccounttypes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='useraccounttypes',
            unique_together={('user', 'account_type')},
        ),
    ]
