# Generated by Django 5.0.6 on 2024-08-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0002_alter_doctorinformation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availibility', models.JSONField()),
                ('doctor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users')),
            ],
        ),
    ]
