# Generated by Django 5.0.6 on 2024-08-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0002_users_created_at_users_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='availability',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
