# Generated by Django 5.0.6 on 2024-08-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0003_remove_doctoravailability_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='doctorInformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to='DocOsge.doctorinformation'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users'),
        ),
    ]
