# Generated by Django 5.0.6 on 2024-08-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0003_doctoravailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
