# Generated by Django 5.0.6 on 2024-07-10 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0004_users_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='last_login',
        ),
    ]
