# Generated by Django 5.0.6 on 2024-08-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0004_appointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
