# Generated by Django 5.0.6 on 2024-08-08 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0004_rename_doctor_id_doctoravailability_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='availibility',
            new_name='availability',
        ),
    ]
