# Generated by Django 5.0.6 on 2024-07-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0005_remove_users_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
    ]
