# Generated by Django 5.0.6 on 2024-08-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0005_alter_doctoravailability_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
