# Generated by Django 5.0.6 on 2024-08-28 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0007_alter_doctoravailability_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='doctor_availability',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_avalability', to='DocOsge.doctoravailability'),
        ),
    ]
