# Generated by Django 5.0.6 on 2024-07-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0008_usergoals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergoals',
            old_name='user_id',
            new_name='user',
        ),
    ]
