# Generated by Django 5.0.6 on 2024-08-30 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0008_appointments_doctor_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='DocOsge.users')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHealthRecordFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_record', to='DocOsge.patienthealthrecords')),
            ],
        ),
    ]
