# Generated by Django 5.0.6 on 2024-08-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0009_patienthealthrecords_patienthealthrecordfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthealthrecordfiles',
            name='file_url',
            field=models.FileField(upload_to='health_records'),
        ),
    ]
