# Generated by Django 5.0.6 on 2024-07-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0009_rename_user_id_usergoals_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGoals',
            new_name='UserInformation',
        ),
    ]
