# Generated by Django 5.0.6 on 2024-08-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0010_alter_patienthealthrecordfiles_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthrecords',
            name='report_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
