# Generated by Django 5.0.6 on 2024-07-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0010_rename_usergoals_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='getInBed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='wakeUp',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
