# Generated by Django 5.0.6 on 2024-08-30 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0011_patienthealthrecords_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthealthrecords',
            name='report_type',
        ),
    ]
