# Generated by Django 5.0.6 on 2024-07-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0011_alter_userinformation_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DocOsge.users', unique=True),
        ),
    ]
