# Generated by Django 5.0.6 on 2024-08-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0012_remove_patienthealthrecords_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthealthrecords',
            name='report_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
