# Generated by Django 5.0.6 on 2024-09-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0013_patienthealthrecords_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
