# Generated by Django 5.0.6 on 2024-09-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0014_alter_doctoravailability_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
