# Generated by Django 5.0.6 on 2024-09-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocOsge', '0016_usermedications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedications',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='usermedications',
            unique_together={('user', 'name')},
        ),
    ]
